apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluentd.conf: |
    <source>
      @type tail
      format none
      path /var/log/1.log
      pos_file /var/log/1.log.pos
      tag count.format1
    </source>

    <source>
      @type tail
      format none
      path /var/log/2.log
      pos_file /var/log/2.log.pos
      tag count.format2
    </source>

    <filter count.**>
      @type record_transformer
      <record>
        pod_name "#{ENV["POD_NAME"]}"
        pod_ip "#{ENV["POD_IP"]}"
        pod_namespace "#{ENV["POD_NAMESPACE"]}"
        node_name "#{ENV["NODE_NAME"]}"
      </record>
    </filter>
    <filter count.**>
      @id filter_kubernetes_metadata
      @type kubernetes_metadata
    </filter>
    <match **>
      @id elasticsearch
      @type elasticsearch
      @log_level info
      type_name _doc
      host elasticsearch
      port 9200
      include_tag_key true
      tag_key @log_name
      logstash_format true
      flush_interval 10s
    </match>