apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: fluentd-sidecar-injector-webhook-cfg
  labels:
    app: fluentd-sidecar-injector
webhooks:
- name: fluentd-sidecar-injector.snailwalker.me
  clientConfig:
    service:
      name: fluentd-sidecar-injector-webhook-svc
      namespace: sidecar-injector
      path: "/mutate"
    caBundle: ${CA_BUNDLE}
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  namespaceSelector:
    matchLabels:
      fluentd-sidecar-injection: enabled
