apiVersion: v1
kind: Service
metadata:
  name: fluentd-sidecar-injector-webhook-svc
  namespace: sidecar-injector
  labels:
    app: fluentd-sidecar-injector
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app: fluentd-sidecar-injector
